-- CreateEnum
CREATE TYPE "Patente" AS ENUM ('SOLDADO_I', 'SOLDADO_II', 'SOLDADO_III', 'CABO_I', 'CABO_II', 'PRIMEIRO_SARGENTO', 'SEGUNDO_SARGENTO', 'TERCEIRO_SARGENTO', 'SUB_OFICIAL', 'ASPIRANTE_OFICIAL', 'PRIMEIRO_TENENTE', 'SEGUNDO_TENENTE', 'CAPITAO', 'MAJOR', 'TENENTE_CORONEL', 'CORONEL', 'GENERAL_DE_BRIGADA', 'GENERAL_DE_DIVISAO', 'GENERAL_DE_EXERCITO', 'MARECHAL');

-- CreateEnum
CREATE TYPE "StatusOperador" AS ENUM ('ATIVO', 'TREINAMENTO', 'INCAPAZ_TEMPORARIO', 'INCAPAZ_PERMANENTE');

-- CreateTable
CREATE TABLE "Operador" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "cpf" INTEGER NOT NULL,
    "patente" "Patente" NOT NULL,
    "status" "StatusOperador" NOT NULL DEFAULT 'ATIVO',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Operador_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Operador_email_key" ON "Operador"("email");
