export enum Patente {
  SOLDADO_I = "SOLDADO_I",
  SOLDADO_II = "SOLDADO_II",
  SOLDADO_III = "SOLDADO_III",
  CABO_I = "CABO_I",
  CABO_II = "CABO_II",
  PRIMEIRO_SARGENTO = "PRIMEIRO_SARGENTO",
  SEGUNDO_SARGENTO = "SEGUNDO_SARGENTO",
  TERCEIRO_SARGENTO = "TERCEIRO_SARGENTO",
  SUB_OFICIAL = "SUB_OFICIAL",
  ASPIRANTE_OFICIAL = "ASPIRANTE_OFICIAL",
  PRIMEIRO_TENENTE = "PRIMEIRO_TENENTE",
  SEGUNDO_TENENTE = "SEGUNDO_TENENTE",
  CAPITAO = "CAPITAO",
  MAJOR = "MAJOR",
  TENENTE_CORONEL = "TENENTE_CORONEL",
  CORONEL = "CORONEL",
  GENERAL_DE_BRIGADA = "GENERAL_DE_BRIGADA",
  GENERAL_DE_DIVISAO = "GENERAL_DE_DIVISAO",
  GENERAL_DE_EXERCITO = "GENERAL_DE_EXERCITO",
  MARECHAL = "MARECHAL"

}