export enum statusMissao {
  ABERTA = "ABERTA",
  ANDAMENTO = "ANDAMENTO",
  FECHADA = "FECHADA",
}

export enum statusOperador {
  ATIVO = "ATIVO",
  TREINAMENTO = "TREINAMENTO",
  INCAPAZ_TEMPORARIO = "INCAPAZ_TEMPORARIO",
  INCAPAZ_PERMANENTE = "INCAPAZ_PERMANENTE",
}